-- AlterTable
ALTER TABLE "general_settings" ALTER COLUMN "workweek_starts_on" SET DEFAULT 1,
ALTER COLUMN "working_hours_calculation" SET DEFAULT E'FIRSTLAST';

-- AlterTable
ALTER TABLE "workweeks" ALTER COLUMN "saturday" SET DEFAULT false,
ALTER COLUMN "saturday_start_time" SET DEFAULT E'00:00',
ALTER COLUMN "saturday_start_time" SET DATA TYPE TEXT,
ALTER COLUMN "saturday_end_time" SET DEFAULT E'00:00',
ALTER COLUMN "saturday_end_time" SET DATA TYPE TEXT,
ALTER COLUMN "friday" SET DEFAULT true,
ALTER COLUMN "friday_end_time" SET DEFAULT E'00:00',
ALTER COLUMN "friday_end_time" SET DATA TYPE TEXT,
ALTER COLUMN "friday_start_time" SET DEFAULT E'00:00',
ALTER COLUMN "friday_start_time" SET DATA TYPE TEXT,
ALTER COLUMN "monday" SET DEFAULT true,
ALTER COLUMN "monday_end_time" SET DEFAULT E'00:00',
ALTER COLUMN "monday_end_time" SET DATA TYPE TEXT,
ALTER COLUMN "monday_start_time" SET DEFAULT E'00:00',
ALTER COLUMN "monday_start_time" SET DATA TYPE TEXT,
ALTER COLUMN "sunday" SET DEFAULT false,
ALTER COLUMN "sunday_end_time" SET DEFAULT E'00:00',
ALTER COLUMN "sunday_end_time" SET DATA TYPE TEXT,
ALTER COLUMN "sunday_start_time" SET DEFAULT E'00:00',
ALTER COLUMN "sunday_start_time" SET DATA TYPE TEXT,
ALTER COLUMN "thursday" SET DEFAULT true,
ALTER COLUMN "thursday_end_time" SET DEFAULT E'00:00',
ALTER COLUMN "thursday_end_time" SET DATA TYPE TEXT,
ALTER COLUMN "thursday_start_time" SET DEFAULT E'00:00',
ALTER COLUMN "thursday_start_time" SET DATA TYPE TEXT,
ALTER COLUMN "tuesday" SET DEFAULT true,
ALTER COLUMN "tuesday_end_time" SET DEFAULT E'00:00',
ALTER COLUMN "tuesday_end_time" SET DATA TYPE TEXT,
ALTER COLUMN "tuesday_start_time" SET DEFAULT E'00:00',
ALTER COLUMN "tuesday_start_time" SET DATA TYPE TEXT,
ALTER COLUMN "wednesday" SET DEFAULT true,
ALTER COLUMN "wednesday_end_time" SET DEFAULT E'00:00',
ALTER COLUMN "wednesday_end_time" SET DATA TYPE TEXT,
ALTER COLUMN "wednesday_start_time" SET DEFAULT E'00:00',
ALTER COLUMN "wednesday_start_time" SET DATA TYPE TEXT;
